<?php

namespace Database\Seeders;

use App\Models\Branch;
use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    public function run(): void
    {
        $branches = [
            [
                'name_km' => '១. សាខាភ្នំពេញ',
                'name_en' => '1. Phnom Penh Branch',
                'type' => 'branch',
                'city' => 'PHNOM PENH',
                'city_km' => 'រាជធានីភ្នំពេញ',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'រាជធានីភ្នំពេញ, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Phnom Penh, Kingdom of Cambodia',
                'province_km' => 'រាជធានីភ្នំពេញ',
                'province_en' => 'Phnom Penh',
                'phone' => '012 675 775',
                'email' => 'phnompenh.branch@telnet.com.kh',
                'lat' => 11.5564,
                'lng' => 104.9282,
                'sort_order' => 1,
            ],

            [
                'name_km' => '២. សាខាកណ្ដាល',
                'name_en' => '2. Kandal Branch',
                'type' => 'branch',
                'city' => 'KANDAL',
                'city_km' => 'ខេត្តកណ្ដាល',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តកណ្ដាល, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Kandal Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តកណ្ដាល',
                'province_en' => 'Kandal',
                'phone' => '012 675 776',
                'email' => 'kandal.branch@telnet.com.kh',
                'lat' => 11.5730,
                'lng' => 104.9230,
                'sort_order' => 2,
            ],

            [
                'name_km' => '៣. សាខាបាត់ដំបង',
                'name_en' => '3. Battambang Branch',
                'type' => 'branch',
                'city' => 'BATTAMBANG',
                'city_km' => 'ខេត្តបាត់ដំបង',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តបាត់ដំបង, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Battambang Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តបាត់ដំបង',
                'province_en' => 'Battambang',
                'phone' => '012 675 777',
                'email' => 'battambang.branch@telnet.com.kh',
                'lat' => 13.0957,
                'lng' => 103.2022,
                'sort_order' => 3,
            ],

            [
                'name_km' => '៤. សាខាសៀមរាប',
                'name_en' => '4. Siem Reap Branch',
                'type' => 'branch',
                'city' => 'SIEM REAP',
                'city_km' => 'ខេត្តសៀមរាប',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តសៀមរាប, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Siem Reap Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តសៀមរាប',
                'province_en' => 'Siem Reap',
                'phone' => '012 675 778',
                'email' => 'siemreap.branch@telnet.com.kh',
                'lat' => 13.3671,
                'lng' => 103.8448,
                'sort_order' => 4,
            ],

            [
                'name_km' => '៥. សាខាកំពង់ស្ពឺ',
                'name_en' => '5. Kampong Speu Branch',
                'type' => 'branch',
                'city' => 'KAMPONG SPEU',
                'city_km' => 'ខេត្តកំពង់ស្ពឺ',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តកំពង់ស្ពឺ, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Kampong Speu Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តកំពង់ស្ពឺ',
                'province_en' => 'Kampong Speu',
                'phone' => '012 675 779',
                'email' => 'kampongspeu.branch@telnet.com.kh',
                'lat' => 11.4533,
                'lng' => 104.5209,
                'sort_order' => 5,
            ],

            [
                'name_km' => '៦. សាខាកំពង់ធំ',
                'name_en' => '6. Kampong Thom Branch',
                'type' => 'branch',
                'city' => 'KAMPONG THOM',
                'city_km' => 'ខេត្តកំពង់ធំ',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តកំពង់ធំ, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Kampong Thom Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តកំពង់ធំ',
                'province_en' => 'Kampong Thom',
                'phone' => '012 675 780',
                'email' => 'kampongthom.branch@telnet.com.kh',
                'lat' => 12.2500,
                'lng' => 104.6667,
                'sort_order' => 6,
            ],

            [
                'name_km' => '៧. សាខាកំពត',
                'name_en' => '7. Kampot Branch',
                'type' => 'branch',
                'city' => 'KAMPOT',
                'city_km' => 'ខេត្តកំពត',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តកំពត, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Kampot Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តកំពត',
                'province_en' => 'Kampot',
                'phone' => '012 675 781',
                'email' => 'kampot.branch@telnet.com.kh',
                'lat' => 10.6104,
                'lng' => 104.1815,
                'sort_order' => 7,
            ],

            [
                'name_km' => '៨. សាខាព្រះសីហនុ',
                'name_en' => '8. Preah Sihanouk Branch',
                'type' => 'branch',
                'city' => 'PREAH SIHANOUK',
                'city_km' => 'ខេត្តព្រះសីហនុ',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តព្រះសីហនុ, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Preah Sihanouk Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តព្រះសីហនុ',
                'province_en' => 'Preah Sihanouk',
                'phone' => '012 675 782',
                'email' => 'sihanoukville.branch@telnet.com.kh',
                'lat' => 10.6251,
                'lng' => 103.5238,
                'sort_order' => 8,
            ],

            [
                'name_km' => '៩. សាខាកំពង់ចាម',
                'name_en' => '9. Kampong Cham Branch',
                'type' => 'branch',
                'city' => 'KAMPONG CHAM',
                'city_km' => 'ខេត្តកំពង់ចាម',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តកំពង់ចាម, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Kampong Cham Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តកំពង់ចាម',
                'province_en' => 'Kampong Cham',
                'phone' => '012 675 783',
                'email' => 'kampongcham.branch@telnet.com.kh',
                'lat' => 11.9934,
                'lng' => 105.4635,
                'sort_order' => 9,
            ],

            [
                'name_km' => '១០. សាខាតាកែវ',
                'name_en' => '10. Takeo Branch',
                'type' => 'branch',
                'city' => 'TAKEO',
                'city_km' => 'ខេត្តតាកែវ',
                'country' => 'Cambodia',
                'country_km' => 'ព្រះរាជាណាចក្រកម្ពុជា',
                'address_km' => 'ខេត្តតាកែវ, ព្រះរាជាណាចក្រកម្ពុជា',
                'address_en' => 'Takeo Province, Kingdom of Cambodia',
                'province_km' => 'ខេត្តតាកែវ',
                'province_en' => 'Takeo',
                'phone' => '012 675 784',
                'email' => 'takeo.branch@telnet.com.kh',
                'lat' => 10.9908,
                'lng' => 104.7847,
                'sort_order' => 10,
            ],
        ];

        foreach ($branches as $branch) {
            Branch::firstOrCreate(['name_km' => $branch['name_km']], $branch);
        }
    }
}
